const filterData = {
  locations: [
    "Jura",
    "Neuchâtel",
    "Vaud",
    "Geneva",
    "Bern",
    "Fribourg",
    "Valais",
  ],
  categories: ["Children", "Youth", "Adults", "Seniors"],
  levels: [
    "U-7 - Young beginners",
    "U-9 - 7-8 years old",
    "U-11 - 9-10 years old",
    "U-13 - 11-12 years old",
    "U-15 - 13-14 years old",
    "U-17 - 15-16 years old",
    "U-19 - 17-18 years old",
    "U-21 - 19-20 years old",
    "Regional amateur leagues",
    "Lower amateur leagues",
    "High-level amateur leagues",
    "Semi-Professional",
  ],
  licenses: [
    "Futsal Coach Level 1",
    "Physical Trainer Level 3",
    "Goalkeeper Coach Level 2 Youth",
    "Goalkeeper License A",
    "Children's sports expert",
    "Further training 2",
    "Diploma D",
    "C basic",
    "UEFA C",
    "B UEFA",
    "B UEFA Youth",
    "UEFA A",
    "UEFA Youth A",
    "UEFA Pro Licence",
  ],
};

export default filterData;
